version: "2"
services:
  php-app:
    build: ./docker/php
    volumes:
      - ./laravel:/var/www/html
  nginx-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html
      - ./proxy/conf.d:/etc/nginx/conf.d
    links:
      - php-app:php-app
      - mysql:mysql
  mysql:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345
  node-install:
    image: node:slim
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: npm install
  mix-build:
    image: node:slim
    volumes:
      - ./laravel:/app
    working_dir: /app
    command: npm run dev